[package]
name = "gtktok"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-Only"
authors = [
    "Max Rodriguez <me@maxrdz.com>"
]
repository = "https://github.com/maxrdz/gtktok" 
homepage = "https://github.com/maxrdz/gtktok"

[dependencies]
gtk = { version = "0.7", package = "gtk4" }
tiktok-api = { version = "0.3" }

[profile.release]
codegen-units = 1 # Best LLVM optimization
panic = "abort" # Remove unwind code on release
opt-level = 3
lto = true
strip = true
