[package]
name = "tuxtok"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = [
    "Max Rodriguez <me@maxrdz.com>",
    "vkill <vkill.net@gmail.com>",
]
repository = "https://github.com/maxrdz/gtktok" 
homepage = "https://github.com/maxrdz/gtktok"

[dependencies]
libadwaita = { version = "0.5", features = ["v1_4"] }
tiktok-api = { version = "0.3" }

[profile.release]
codegen-units = 1 # Best LLVM optimization
panic = "abort" # Remove unwind code on release
opt-level = 3
lto = true
strip = true
